Canonicalize symlinked paths to rbenv executable
rbenv/rbenv-installer pull request #49
Opened 2023-09-19 19:33 UTC by devstuff

# Problem:

If `rbenv-doctor` is downloaded and installed locally, running `rbenv doctor` results in a warning:

```
Checking for `rbenv' in PATH: multiple
  You seem to have multiple rbenv installs in the following locations.
  Please pick just one installation and remove the others.
  
  /usr/local/Cellar/rbenv/1.2.0/libexec/rbenv
  /usr/local/bin/rbenv
```

The Homebrew installation has `/usr/local/bin/rbenv` symlinked to `/usr/local/Cellar/rbenv/1.2.0/libexec/rbenv`.

# Fix:

Canonicalizing symlinks results in a single canonical path:

```
Checking for `rbenv' in PATH: /usr/local/Cellar/rbenv/1.2.0/libexec/rbenv
```

**NOTE:** running the command directly via `curl`, as per the README, results in a single path:

```
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
```

Running the command directly as `/some/path/rbenv-doctor` results in a single path. When launched via `rbenv` is when the multiple paths are detected.

I assume this discrepancy may be related to my environment, but the canonicalized path is the correct result.

2025-04-02 21:16 UTC, saltman007web approved these changes

2025-04-03 14:51 UTC, mislav requested changes
Hi, thanks for the contribution! This looks good so far, but I'm thinking that it can be simplified: how about having `command-list` print the list of canonicalized paths in the first place? That way we can remove the hack that is `fix-usr-bin`.

Something like:
```sh
local path
which -a "$1" | while read -r path; do
  readlink -f "$path" 2>/dev/null || printf '%s\n' "$path"
done
```

2025-04-03 14:52 UTC, mislav commented
Sorry, I just realized I'm responding to a years-old PR (by accident, I haven't been watching this repo until now). I don't expect you to make the requested changes; instead I will apply them on top of your branch.

2025-04-04 04:47 UTC, saltman007web approved these changes

2025-04-09 19:46 UTC, merged